react-native-push-notification/ios

.circleci/config.yml, .eslintignore, .eslintrc.js, .prettierrc.js, babel.config.js, example/App.js, js/index.js, package.json, yarn.lock
Added eslint and prettier to the repository and ci-check
- yarn lint
- circle ci
=> Add eslint and prettier

js/index.js
I was getting ESLint errors on the import statement for this package. (see [rule documentation](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md).)
Technically, to use the suggested import syntax:
```js
import PushNotificationIOS from '@react-native-community/push-notification-ios';
```
the package should have an `export default`.
And since you are already using ES6 import statements, it won't harm compatibility.
=> Use proper ES6 default export

js/index.js
This is based on [Delete deprecated `$Enum<...>` utility type](https://github.com/facebook/flow/commit/764a4fb75466ab0462f63bab1a755ff3e0a6e3f9)
Not required
=> Change $Enum to $Keys to correct flow errors

.circleci/config.yml, index.d.ts, package.json, tsconfig.json
This PR is to address #59 
Changed type export from `export = ` to `export default`
This will fix the tsc build error for push-notification-ios
Also added type-check for CI.
yarn test:tsc
=> Fix type and added type-check to CI

index.d.ts
The original PushNotificationIOS from react-native package was taking a `Date` object for `fireDate`. Using such an object with this new package however throws an exception "NSmutableDictionary cannot be converted to date".
=> Fix defintion of fireDate

index.d.ts
Add Missing type definition based on the information on document http://facebook.github.io/react-native/docs/pushnotificationios.html#schedulelocalnotification
=> fix: add missing type definitions

docs/manual-linking.md, index.d.ts, js/index.js
This PR update react native docs links to new domain: reactnative.dev
Open link in changed files
=> docs: update documentation links to reactnative.dev

ios/RNCPushNotificationIOS.h, ios/RNCPushNotificationIOS.m
Applying changes from this commit https://github.com/facebook/react-native/commit/edfdafc7a14e88a2660b95cb220c62f29b1b28c0
Replacing Apple-deprecated notification method with UNUserNotificationCenter.currentNotificationCenter
I will test this branch locally and apply changes to the example in #51
=> feat: replace apple-deprecated notification method

ios/RNCPushNotificationIOS.m
Fixed the code errors breaking the build with the last merge of #66 
Use the last merge fbcb2e7c4a42f2e3e24f9f456b93f16918e9efd7 and app won't build
Just try to build
=> Fix code errors breaking the build

.circleci/config.yml, README.md, RNCPushNotificationIOS.podspec, example/android/app/build.gradle, index.d.ts, package.json
update url for the new repo
updated podspec working with with example
=> docs: update url for new repo name

example/App.js, example/ios/example/AppDelegate.m
Updated example to use function component, and updated `AppDelegate.m` in the example to get the local notification running.
=> chore(example): update example to function component

ios/RNCPushNotificationIOS.m
iOS throws a warning that registerForRemoteNotifications must be called
from the main thread only, this just wraps that call in a block to
ensure it always runs there, regardless of how the containing function
is called.
Ran on a device under debug and saw the thread safety warning go away
Physical device
Call the method below from a thread other than the main UI thread:
`
RCT_EXPORT_METHOD(requestPermissions:(NSDictionary *)permissions
resolver:(RCTPromiseResolveBlock)resolve
rejecter:(RCTPromiseRejectBlock)reject)
`
- [X ] I have tested this on a device and a simulator
=> chore: Use main thread for requesting notification permissions.

.circleci/config.yml, js/index.js, package.json, yarn.lock
Updating eslint-config to latest 1.0.0 and typescript to latest 3.8.3
Lint and type-check passes
=> chore: update lint config and typescript

js/index.js
Adding Error message in development mode if PushNotificationIOS is being used when PushNotificationManager is not available.
This change is for debugging purpose and it will not affect production code
Invariant Error Message displays
=> chore: add error message when not in production mode

README.md, example/ios/example/AppDelegate.m, ios/RNCPushNotificationIOS.h, ios/RNCPushNotificationIOS.m
Closes https://github.com/react-native-community/push-notification-ios/issues/102https://github.com/react-native-community/push-notification-ios/issues/102
Local notification event is being managed by depreciated method. To make this work I have added support for new method used to handle local notification clicks.
I have implemented this feature in the same way the other local notification event was built.
This does not have any breaking changes as I implemented a new method that is used for IOS 10+
- Local notification event should work on IOS 10+ with new `didReceiveNotificationResponse` and prior to IOS 10 using old `didReceiveLocalNotification` method.
- We need to ensure `localNotification` event is being fired when tapping local notification on a device with IOS 10.
- To support …
=> Handling local notification event for IOS 10+

example/App.js, example/ios/Podfile, example/ios/Podfile.lock, example/ios/example.xcodeproj/project.pbxproj, example/ios/example.xcodeproj/xcshareddata/xcschemes/example-tvOS.xcscheme, example/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme, example/ios/example/AppDelegate.h, example/ios/example/Images.xcassets/AppIcon.appiconset/Contents.json, example/ios/example/Info.plist, example/ios/example/exampleDebug.entitlements, example/ios/example/exampleRelease.entitlements
I've just updated and configured the example project to meet the set up requirements of this library.
~~Besides everything is set upped as it should be it still doesnt work on iOS 13.1.3 with my real iPhone 7 device~~. Fixed by #97
=> Example project fixes

js/index.js
We need to have a` fireDate` in the response of the notification. It is impossible to figure out what date or time it was triggered without  `fireDate`
=> fix return notification fireDate

example/App.js
presentNotification does not take prop `fireDate`, as notification is fired immediately
=> chore: fix example

ios/RNCPushNotificationIOS.m
Currently, when called method `getScheduledLocalNotifications` there are no fields to see title or repeatInterval of scheduled notification. This PR adds those missing pieces. I think it will be very helpful for managing local notifications.
=> feat: Add alertTitle, repeatInterval to formatted notification

README.md, example/App.js, ios/RNCPushNotificationIOS.m
=> add changes for next version

ios/RNCPushNotificationIOS.m
Fixes `Incompatible operand types ('NSUInteger' (aka 'unsigned long') and 'id')` on repeat interval.
Looks like my CocoaPods were cached when testing. With cleaned build cache current version doesn't build. My bad...
This needs to be released as a hotfix 😞 
@Naturalclar
=> fix iOS build breaking

example/App.js, example/ios/Podfile.lock, example/ios/example/AppDelegate.m, package.json, yarn.lock
Updated the community eslint-config to latest version
Also Added example usage of alertTitle
=> chore: update example and lint

README.md, ios/RNCPushNotificationIOS.m
I was working on a project and needed access to know if notifications were enabled for `lockScreen` and `notificationCenter` when firing `checkPermissions()`.
To test fire `checkPermissions()` and you should get an updated object that includes `lockScreen` and `notificationCenter`. 
Alternatively, you can also run the `/example` and press "show enabled permissions".
Before this commit:
```
{
"alert": true,
"badge": true,
"sound": true,
}
```
After commit:
```
{
"alert": true,
"badge": true,
"sound": true,
"lockScreen": true, 
"notificationCenter": true,
}
```
=> Added support for checking if lockScreen and notificationCenter settings are enabled

README.md, index.d.ts, js/index.js
Currently, we can access notification's `alertBody` by using `getAlert()` or `getMessage()`, but there is no method for getting the `alertTitle`in JavaScript side. This PR adds that missing piece. 
| iOS     |    ✅    |
=> Add method getTitle to get notification title in JS

example/App.js, example/ios/Podfile.lock
Added example of `getTitle` method added in #157 
=> chore: add example for getTitle method

README.md, example/App.js, ios/RNCPushNotificationIOS.m
In my app I need to run some JS code after user clicked on local notification. I didn't find any way to determine the moment user clicked on it.
This PR adds additional `userInteraction` attribute to userInfo for push messages that was opened by user.
If somebody approve this changes, I'll add an example.
=> Add userInteraction attr for user opened push

RNCPushNotificationIOS.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
=> fix: Xcode 12 compatibility

README.md, index.d.ts, ios/RNCPushNotificationIOS.m, js/index.js
I need to know whether user has determined the notification permission (i.e. whether user has went through the "Don't Allow/Allow' permission modal)
Run the `/example` and press "show enabled permissions".
Before this commit:
```
{
"alert": true,
"badge": true,
"sound": true,
"lockScreen": true, 
"notificationCenter": true,
}
```
After commit:
```
{
"alert": true,
"badge": true,
"sound": true,
"lockScreen": true, 
"notificationCenter": true,
"authorizationStatus": 0,
}
```
=> Add authorizationStatus in permissions object

README.md
the constants used in the readme are those for requesting permissions from user, not for displaying a notification
=> fix completion handler constants

index.d.ts
`AuthorizationStatus` in `PushNotificationPermissions` is actually a number value not whole interface. I made `PushNotificationPermissions` to include values from this interface
=> Fix issue #196

ios/RNCPushNotificationIOS.m
the current implementation of [didReceiveNotificationResponse](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc) which "Asks the delegate to process the user's response to a delivered notification." ignores the user response.
This fixes the issue, and user's action identifier will be present in `actionIdentifier` field in the JS event payload.
=> feat: include response actionIdentifier in event

example/ios/Podfile.lock
Updated podfile lock as example project was not working when building with Xcode 12
=> chore: update podfile.lock

README.md, example/App.js, index.d.ts, ios/RNCPushNotificationIOS.m, js/index.js
Fix #201 
Added `removeAllPendingNotificationRequests` method to replace the deprecated `cancelAllNotifications` method.
cancelAllNotifications method will be removed in the next major version of this package
=> feat: add removeAllPendingNotificationRequests method

ios/RNCPushNotificationIOS.m
fix crash that occurs when user responds to non-textinput action
=> fix: crash on non-textinput action

README.md, example/App.js, example/ios/example/AppDelegate.m
Since the package only supports iOS10+, I've removed instructions for pre iOS10 devices
=> docs: remove pre iOS10 information from README

example/App.js, index.d.ts, ios/RNCPushNotificationIOS.m, js/index.js, js/types.js
Closes #41
Allows users to add threadId to local notification request
=> feat: add threadIdentifier for local notification

ios/RNCPushNotificationIOS.h, ios/RNCPushNotificationIOS.m
Uncommented exception for UIKITFORMAC to allow mac catalyst builds
=> feat: allow mac catalyst build

ios/RNCPushNotificationIOS.m
Currrently userInteraction is false even though the app is started via tapping the notification to start the app.
=> set userInteraction on initial notification

.flowconfig, example/App.js, js/index.js, js/types.js, package.json, yarn.lock
updated flowtype to latest version
=> chore: update flowtype

example/ios/Podfile, example/ios/Podfile.lock, example/ios/example.xcodeproj/project.pbxproj
updated minimum iOS version of example to match the minimum version of push-notification-ios module
=> chore: update iOS version of example

ios/RNCPushNotificationIOS.m
Add badge and sound to RCTFormatUNNotification and RCTFormatUNNotificationRequest in order to return the same properties formatted by RCTFormatLocalNotification.
=> Add badge and sound to UNNotification and UNNotificationRequest formatters

ios/RNCPushNotificationIOS.m
may resolve #163
related issues
https://github.com/invertase/react-native-firebase/issues/3944
https://github.com/firebase/firebase-ios-sdk/pull/6863
=> fix: avoid crash on iOS 14 when push comes on foreground

.github/workflows/ci.yml, example/ios/example/AppDelegate.m, ios/RNCPushNotificationIOS.m
address #163 
removed completionHandler from onFinishRemoteNotification
=> fix: remove completionHandler from finish

README.md, example/App.js, index.d.ts, ios/RNCPushNotificationIOS.m, js/index.js
#239 
added `removePendingNotificationRequests` method
=> feat: add removePendingNotificationRequests method

README.md, index.d.ts, ios/RCTConvert+Notification.m, ios/RNCPushNotificationIOS.m, js/index.js
Should fix https://github.com/react-native-push-notification-ios/push-notification-ios/issues/225
=> Add support for critical notifications

README.md, example/ios/Podfile.lock, example/ios/example.xcodeproj/project.pbxproj, index.d.ts, ios/RCTConvert+Notification.m, js/types.js
Continued work from #268 
Added year and day of week repetition, and removed nanosecond option.
=> feat: add day of the week and year repetition

ios/RNCPushNotificationIOS.m
Fix crash caused on iOS 11 by not supporting "criticalAlertSetting" which was added for iOS 12.
=> Fix for invalid selector on iOS11

README.md, ios/RCTConvert+Notification.m, js/types.js
This is a PR to add an optional parameter to make local notifications timezone agnostic, if a notification is scheduled for 8 pm, it will trigger at 8 pm, no matter if you are in LA or NYC. I currently have it set as "isTimeZoneAgnostic", maybe "isTimeZoneIndependent", definitely open to feedback on this. I updated the docs as well, let me know if there is anything else.
=> Make notifications time zone agnostic

ios/RCTConvert+Notification.h, ios/RCTConvert+Notification.m
iOS introduced a new feature called Focus modes in which notifications don't make a sound and don't wake up the screen unless notifications are marked time-sensitive. Notifications can be marked time-sensitive by providing an `interruptionLevel`. Added support to provide `interruptionLevel` while adding a notification request.
Fixes #345
=> parse interruptionLevel field to allow time-sensitive notifications

README.md
Add install instruction for React Native v0.71
=> docs: add instruction for RN 71

index.d.ts
This was added by https://github.com/react-native-push-notification/ios/pull/354 and just didn't have updated typescript types.
=> [typescript] Add isTimeZoneAgnostic in Typescript types
